import { Routes } from '@angular/router';

import { authGuard, guestGuard } from './core/auth.guard';

export const routes: Routes = [
  { path: '', pathMatch: 'full', loadComponent: () => import('./pages/entry.page').then(m => m.EntryPage), canActivate: [guestGuard] },
  { path: 'auth/login', loadComponent: () => import('./pages/login.page').then(m => m.LoginPage), canActivate: [guestGuard] },
  { path: 'auth/register-policy', loadComponent: () => import('./pages/register-policy.page').then(m => m.RegisterPolicyPage), canActivate: [guestGuard] },
  { path: 'login', redirectTo: 'auth/login', pathMatch: 'full' },
  {
    path: 'app',
    loadComponent: () => import('./shell/app-shell.component').then(m => m.AppShellComponent),
    canActivate: [authGuard],
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'overview' },
      { path: 'overview', loadComponent: () => import('./pages/command-center.page').then(m => m.CommandCenterPage) },
      { path: 'metrics', loadComponent: () => import('./pages/executive-metrics.page').then(m => m.ExecutiveMetricsPage) },
      { path: 'tasks', loadComponent: () => import('./pages/operations-tasks.page').then(m => m.OperationsTasksPage) },
      { path: 'inventory/products', loadComponent: () => import('./pages/materials.page').then(m => m.MaterialsPage) },
      { path: 'inventory/products/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'products' } },
      { path: 'inventory/stock', loadComponent: () => import('./pages/warehouse-flow.page').then(m => m.WarehouseFlowPage) },
      { path: 'inventory/stock/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'stock' } },
      { path: 'inventory/replenishment', loadComponent: () => import('./pages/replenishment.page').then(m => m.ReplenishmentPage) },
      { path: 'inventory/replenishment/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'replenishment' } },
      { path: 'sales/orders', loadComponent: () => import('./pages/fulfillment.page').then(m => m.FulfillmentPage) },
      { path: 'sales/orders/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'salesOrders' } },
      { path: 'sales/kanban', redirectTo: 'sales/orders', pathMatch: 'full' },
      { path: 'procurement/orders', loadComponent: () => import('./pages/procurement.page').then(m => m.ProcurementPage) },
      { path: 'procurement/orders/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'purchaseOrders' } },
      { path: 'suppliers/performance', loadComponent: () => import('./pages/supplier-performance.page').then(m => m.SupplierPerformancePage) },
      { path: 'dispatch', loadComponent: () => import('./pages/dispatch-center.page').then(m => m.DispatchCenterPage) },
      { path: 'data-quality', loadComponent: () => import('./pages/data-quality.page').then(m => m.DataQualityPage) },
      { path: 'quality', loadComponent: () => import('./pages/quality-inspection.page').then(m => m.QualityInspectionPage) },
      { path: 'customers', loadComponent: () => import('./pages/customer-operations.page').then(m => m.CustomerOperationsPage) },
      { path: 'customers/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'customers' } },
      { path: 'capacity', loadComponent: () => import('./pages/capacity-planning.page').then(m => m.CapacityPlanningPage) },
      { path: 'maintenance', loadComponent: () => import('./pages/maintenance.page').then(m => m.MaintenancePage) },
      { path: 'contracts', loadComponent: () => import('./pages/contract-collection.page').then(m => m.ContractCollectionPage) },
      { path: 'service', loadComponent: () => import('./pages/service-workorders.page').then(m => m.ServiceWorkordersPage) },
      { path: 'rules', loadComponent: () => import('./pages/rules-engine.page').then(m => m.RulesEnginePage) },
      { path: 'integrations', loadComponent: () => import('./pages/integration-monitor.page').then(m => m.IntegrationMonitorPage) },
      { path: 'budget', loadComponent: () => import('./pages/budget-cost.page').then(m => m.BudgetCostPage) },
      { path: 'mobile-terminal', loadComponent: () => import('./pages/mobile-terminal.page').then(m => m.MobileTerminalPage) },
      { path: 'finance/receivables', loadComponent: () => import('./pages/receivables.page').then(m => m.ReceivablesPage) },
      { path: 'finance/receivables/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'receivables' } },
      { path: 'finance/credits', loadComponent: () => import('./pages/credit.page').then(m => m.CreditPage) },
      { path: 'finance/credits/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'credits' } },
      { path: 'stocktakes', loadComponent: () => import('./pages/stocktake.page').then(m => m.StocktakePage) },
      { path: 'stocktakes/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'stocktakes' } },
      { path: 'reports', loadComponent: () => import('./pages/reports.page').then(m => m.ReportsPage) },
      { path: 'reports/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'reports' } },
      { path: 'files', loadComponent: () => import('./pages/files.page').then(m => m.FilesPage) },
      { path: 'files/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'files' } },
      { path: 'content/articles', loadComponent: () => import('./pages/content.page').then(m => m.ContentPage) },
      { path: 'content/articles/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'articles' } },
      { path: 'system/users', loadComponent: () => import('./pages/security.page').then(m => m.SecurityPage) },
      { path: 'system/users/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'users' } },
      { path: 'system/audit', loadComponent: () => import('./pages/audit.page').then(m => m.AuditPage) },
      { path: 'system/audit/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'auditLogs' } },
      { path: 'notifications', loadComponent: () => import('./pages/notifications.page').then(m => m.NotificationsPage) },
      { path: 'notifications/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'notifications' } },
      { path: 'ai', loadComponent: () => import('./pages/ai.page').then(m => m.AiPage) },
      { path: 'ai/:id', loadComponent: () => import('./pages/record-detail.page').then(m => m.RecordDetailPage), data: { detail: 'aiSessions' } },
      { path: 'profile', loadComponent: () => import('./pages/profile.page').then(m => m.ProfilePage) },
      { path: 'settings', loadComponent: () => import('./pages/settings.page').then(m => m.SettingsPage) }
    ]
  },
  { path: 'dashboard', redirectTo: 'app/overview', pathMatch: 'full' },
  { path: 'inventory', redirectTo: 'app/inventory/products', pathMatch: 'full' },
  { path: 'sales', redirectTo: 'app/sales/orders', pathMatch: 'full' },
  { path: 'purchase', redirectTo: 'app/procurement/orders', pathMatch: 'full' },
  { path: 'finance', redirectTo: 'app/finance/receivables', pathMatch: 'full' },
  { path: 'stocktake', redirectTo: 'app/stocktakes', pathMatch: 'full' },
  { path: 'reports', redirectTo: 'app/reports', pathMatch: 'full' },
  { path: 'files', redirectTo: 'app/files', pathMatch: 'full' },
  { path: 'system', redirectTo: 'app/system/users', pathMatch: 'full' },
  { path: '**', redirectTo: '' }
];
