"""Add purchase finance stocktake notification models

Revision ID: 65cf96d20fca
Revises: 6b249edb2e25
Create Date: 2025-12-02 00:30:16.850653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cf96d20fca'
down_revision = '6b249edb2e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_performance',
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('on_time_orders', sa.Integer(), nullable=True),
    sa.Column('quality_pass_orders', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('last_order_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['biz_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id')
    )
    with op.batch_alter_table('supplier_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_performance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_performance_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('finance_customer_credit',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('used_credit', sa.Float(), nullable=True),
    sa.Column('warning_threshold', sa.Float(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('frozen_reason', sa.String(length=256), nullable=True),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('frozen_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['frozen_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    with op.batch_alter_table('finance_customer_credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_customer_credit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_customer_credit_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('finance_statements',
    sa.Column('statement_no', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('sales_amount', sa.Float(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_statements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_statements_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_statements_statement_no'), ['statement_no'], unique=True)

    op.create_table('generated_reports',
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('report_name', sa.String(length=128), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_reports_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('po_no', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('actual_receive_date', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_no'), ['po_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)

    op.create_table('purchase_price_history',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['biz_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_price_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_price_history_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('report_subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('send_notification', sa.Boolean(), nullable=True),
    sa.Column('send_hour', sa.Integer(), nullable=True),
    sa.Column('send_weekday', sa.Integer(), nullable=True),
    sa.Column('send_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_subscriptions_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stock_alerts',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_qty', sa.Integer(), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=True),
    sa.Column('suggested_qty', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_alerts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_alerts_status'), ['status'], unique=False)

    op.create_table('stock_takes',
    sa.Column('take_no', sa.String(length=32), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('take_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('category_ids', sa.JSON(), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('counted_items', sa.Integer(), nullable=True),
    sa.Column('variance_items', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_takes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_takes_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_takes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_takes_take_no'), ['take_no'], unique=True)

    op.create_table('sys_notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('related_type', sa.String(length=32), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_notifications_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('finance_receivables',
    sa.Column('receivable_no', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['trade_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_receivables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_receivables_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_receivables_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_receivables_receivable_no'), ['receivable_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_finance_receivables_status'), ['status'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('received_qty', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stock_replenishment_suggestions',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('current_qty', sa.Integer(), nullable=True),
    sa.Column('suggested_qty', sa.Integer(), nullable=True),
    sa.Column('avg_daily_sales', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_replenishment_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_replenishment_suggestions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_replenishment_suggestions_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stock_take_history',
    sa.Column('take_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['take_id'], ['stock_takes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_take_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_take_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_take_history_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stock_take_items',
    sa.Column('take_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('system_qty', sa.Integer(), nullable=True),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('shelf_location', sa.String(length=32), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('counted_by', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['counted_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['take_id'], ['stock_takes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_take_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_take_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_take_items_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('finance_payments',
    sa.Column('payment_no', sa.String(length=32), nullable=True),
    sa.Column('receivable_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('reference_no', sa.String(length=64), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['finance_receivables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_payments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_payments_payment_no'), ['payment_no'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_payments_payment_no'))
        batch_op.drop_index(batch_op.f('ix_finance_payments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_finance_payments_created_at'))

    op.drop_table('finance_payments')
    with op.batch_alter_table('stock_take_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_take_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_take_items_created_at'))

    op.drop_table('stock_take_items')
    with op.batch_alter_table('stock_take_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_take_history_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_take_history_created_at'))

    op.drop_table('stock_take_history')
    with op.batch_alter_table('stock_replenishment_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_replenishment_suggestions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_replenishment_suggestions_created_at'))

    op.drop_table('stock_replenishment_suggestions')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_created_at'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('finance_receivables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_receivables_status'))
        batch_op.drop_index(batch_op.f('ix_finance_receivables_receivable_no'))
        batch_op.drop_index(batch_op.f('ix_finance_receivables_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_finance_receivables_created_at'))

    op.drop_table('finance_receivables')
    with op.batch_alter_table('sys_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_sys_notifications_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sys_notifications_created_at'))

    op.drop_table('sys_notifications')
    with op.batch_alter_table('stock_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_takes_take_no'))
        batch_op.drop_index(batch_op.f('ix_stock_takes_status'))
        batch_op.drop_index(batch_op.f('ix_stock_takes_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_takes_created_at'))

    op.drop_table('stock_takes')
    with op.batch_alter_table('stock_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_stock_alerts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_alerts_created_at'))

    op.drop_table('stock_alerts')
    with op.batch_alter_table('report_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_subscriptions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_report_subscriptions_created_at'))

    op.drop_table('report_subscriptions')
    with op.batch_alter_table('purchase_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_price_history_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_purchase_price_history_created_at'))

    op.drop_table('purchase_price_history')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_no'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_created_at'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_generated_reports_created_at'))

    op.drop_table('generated_reports')
    with op.batch_alter_table('finance_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_statements_statement_no'))
        batch_op.drop_index(batch_op.f('ix_finance_statements_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_finance_statements_created_at'))

    op.drop_table('finance_statements')
    with op.batch_alter_table('finance_customer_credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_customer_credit_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_finance_customer_credit_created_at'))

    op.drop_table('finance_customer_credit')
    with op.batch_alter_table('supplier_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_performance_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_supplier_performance_created_at'))

    op.drop_table('supplier_performance')
    # ### end Alembic commands ###
