"""Compatibility exports for legacy ``app.api.auth`` imports."""

from app.platform.auth import (
    ACCESS_COOKIE_NAME,
    CSRF_COOKIE_NAME,
    CSRF_HEADER_NAME,
    MUTATING_METHODS,
    admin_required,
    auth_cookie_options,
    clear_auth_cookies,
    create_access_token,
    csrf_is_valid,
    csrf_required,
    csrf_token_from_request,
    current_api_user,
    decode_access_token,
    generate_csrf_token,
    get_access_token,
    get_bearer_token,
    jwt_required,
    permission_required,
    response_with_cleared_auth,
    set_auth_cookies,
    with_auth_cookies,
)

__all__ = [
    'ACCESS_COOKIE_NAME',
    'CSRF_COOKIE_NAME',
    'CSRF_HEADER_NAME',
    'MUTATING_METHODS',
    'admin_required',
    'auth_cookie_options',
    'clear_auth_cookies',
    'create_access_token',
    'csrf_is_valid',
    'csrf_required',
    'csrf_token_from_request',
    'current_api_user',
    'decode_access_token',
    'generate_csrf_token',
    'get_access_token',
    'get_bearer_token',
    'jwt_required',
    'permission_required',
    'response_with_cleared_auth',
    'set_auth_cookies',
    'with_auth_cookies',
]
