"""Initial migration: 18 business tables

Revision ID: d6f41a4c242a
Revises: 
Create Date: 2025-11-25 01:48:32.207779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f41a4c242a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_departments',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('auth_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_departments_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('auth_permissions',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('auth_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_permissions_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('auth_roles',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_roles_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('biz_categories',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_categories_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('biz_partners',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_partners_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_partners_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_partners_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_partners_type'), ['type'], unique=False)

    op.create_table('biz_tags',
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('biz_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_tags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_tags_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stock_warehouses',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_warehouses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_warehouses_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('auth_users',
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('is_active_user', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['auth_departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_users_username'), ['username'], unique=False)

    op.create_table('biz_products',
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['biz_categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['biz_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_products_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_products_sku'), ['sku'], unique=True)

    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], )
    )
    op.create_table('biz_product_tags',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['biz_tags.id'], )
    )
    op.create_table('cms_articles',
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_articles_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('cms_attachments',
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('filepath', sa.String(length=512), nullable=True),
    sa.Column('mimetype', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cms_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cms_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cms_attachments_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stock_logs',
    sa.Column('transaction_code', sa.String(length=32), nullable=True),
    sa.Column('move_type', sa.String(length=20), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('qty_change', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_logs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_logs_transaction_code'), ['transaction_code'], unique=False)

    op.create_table('stock_quantities',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('shelf_location', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_quantities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_quantities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_quantities_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('sys_ai_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_ai_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_ai_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_ai_logs_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('sys_audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_audit_logs_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('trade_orders',
    sa.Column('order_no', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['biz_partners.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_orders_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_trade_orders_status'), ['status'], unique=False)

    op.create_table('trade_order_items',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_snapshot', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['trade_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['biz_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_order_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_order_items_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_order_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_trade_order_items_created_at'))

    op.drop_table('trade_order_items')
    with op.batch_alter_table('trade_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_orders_status'))
        batch_op.drop_index(batch_op.f('ix_trade_orders_order_no'))
        batch_op.drop_index(batch_op.f('ix_trade_orders_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_trade_orders_created_at'))

    op.drop_table('trade_orders')
    with op.batch_alter_table('sys_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_audit_logs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sys_audit_logs_created_at'))

    op.drop_table('sys_audit_logs')
    with op.batch_alter_table('sys_ai_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_ai_logs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sys_ai_logs_created_at'))

    op.drop_table('sys_ai_logs')
    with op.batch_alter_table('stock_quantities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_quantities_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_quantities_created_at'))

    op.drop_table('stock_quantities')
    with op.batch_alter_table('stock_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_logs_transaction_code'))
        batch_op.drop_index(batch_op.f('ix_stock_logs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_logs_created_at'))

    op.drop_table('stock_logs')
    with op.batch_alter_table('cms_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_attachments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_cms_attachments_created_at'))

    op.drop_table('cms_attachments')
    with op.batch_alter_table('cms_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cms_articles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_cms_articles_created_at'))

    op.drop_table('cms_articles')
    op.drop_table('biz_product_tags')
    op.drop_table('roles_permissions')
    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_products_sku'))
        batch_op.drop_index(batch_op.f('ix_biz_products_name'))
        batch_op.drop_index(batch_op.f('ix_biz_products_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_biz_products_created_at'))

    op.drop_table('biz_products')
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_users_username'))
        batch_op.drop_index(batch_op.f('ix_auth_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_auth_users_email'))
        batch_op.drop_index(batch_op.f('ix_auth_users_created_at'))

    op.drop_table('auth_users')
    with op.batch_alter_table('stock_warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_warehouses_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_warehouses_created_at'))

    op.drop_table('stock_warehouses')
    with op.batch_alter_table('biz_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_tags_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_biz_tags_created_at'))

    op.drop_table('biz_tags')
    with op.batch_alter_table('biz_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_partners_type'))
        batch_op.drop_index(batch_op.f('ix_biz_partners_name'))
        batch_op.drop_index(batch_op.f('ix_biz_partners_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_biz_partners_created_at'))

    op.drop_table('biz_partners')
    with op.batch_alter_table('biz_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_categories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_biz_categories_created_at'))

    op.drop_table('biz_categories')
    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_roles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_auth_roles_created_at'))

    op.drop_table('auth_roles')
    with op.batch_alter_table('auth_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_permissions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_auth_permissions_created_at'))

    op.drop_table('auth_permissions')
    with op.batch_alter_table('auth_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_departments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_auth_departments_created_at'))

    op.drop_table('auth_departments')
    # ### end Alembic commands ###
